/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonButton: typeof import('./components/Button/Button.vue')['default']
    InputInput: typeof import('./components/Input/Input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextTexr: typeof import('./components/Text/Texr.vue')['default']
    TextText: typeof import('./components/Text/Text.vue')['default']
    'TextText.stories': typeof import('./components/Text/Text.stories.vue')['default']
  }
}
